Repository punkpeye/awesome-mcp-servers, pull requests merged in 2024-12, with the labels that each got.

#73 Adding the simple arXiv MCP
  README.md
Labels: New server

#78 Added iOS Simulator server
  README.md
Labels: New server

#79 Updated description of simulator mcp server
  README.md
Labels: documentation

#80 Added terminal mcp server
  README.md
Labels: New server

#77 Adding typescript implementation of kubernetes mcp server
  README.md
Labels: New server

#83 doc: Added another mcp client
  README.md
Labels: new client

#86 Update README-zh.md
  README-zh.md
  README.md
Labels: documentation

#82 docs: add Japanese README
  README-ja.md
  README.md
Labels: documentation

#95 Update README-zh.md
  README-zh.md
Labels: New server

#96 Split out a new category for running commands.
  README.md
Labels: documentation

#103 Add the Metoro MCP server
  README.md
Labels: New server

#94 docs: add tumf/mcp-shell-server to the list of MCP servers in README …
  README-ja.md
  README.md
Labels: New server

#104 Added isaacwasserman/mcp-vegalite-server
  README.md
Labels: New server

#105 Update clients
  README.md
Labels: new client

#106 Add new Shodan MCP server
  README.md
Labels: documentation, New server

#108 add all-in-one-model-context-protocol
  README.md
Labels: New server

#107 Added tevonsb/homeassistant-mcp
  README.md
Labels: New server

#109 add tumf/mcp-text-editor
  README-ja.md
  README.md
Labels: New server

#111 Added snowflake integration
  README.md
Labels: New server

#112 Add SecretiveShell/MCP-searxng
  README.md
Labels: New server

#113 Add airtable-mcp-server integration
  README-ja.md
  README-zh.md
  README.md
Labels: New server

#115 Updated icon to typescript
  README.md
Labels: documentation

#117 Added Mac Apps Launcher
  README.md
Labels: New server

#121 Add ZeparHyfar/mcp-datetime
  README.md
Labels: New server

#120 Add Node.js-based MCP MySQL server
  README.md
Labels: New server

#118 Add VirusTotal and Maigret MCP Servers
  README.md
Labels: New server

#123 Added app store connect server
  README.md
Labels: New server

#132 add(Developer Tools): sammcj/mcp-package-version
  README.md
Labels: New server

#133 Added LangChain.js client
  README.md
Labels: New server

#131 Add pinecone based mcp server
  README.md
Labels: New server

#129 Add mcp-git-ingest
  README.md
Labels: New server

#127 Add three new MCP servers for iMessage, SQLite, and Documentation RAG
  README.md
Labels: New server

#122 Add cognee MCP to memory list
  README.md
Labels: New server

#126 Update README.md to add link to a clojars mcp server
  README.md
Labels: New server

#125 Add "console-chat-gpt" client
  README.md
Labels: new client

#124 Add "mcp-aoai-web-browsing" server
  README.md
Labels: New server

#116 Fixed name of rectalogic/langchain-mcp
  README.md
Labels: documentation

#130 Add Contentful MCP server to "Other"
  README.md
Labels: New server

#134 Update README-zh.md
  README-zh.md
Labels: documentation

#128 Add mcp-twikit
  README.md
Labels: question, New server

#139 Add a C# .NET SDK for building MCP servers
  README-ja.md
  README-zh.md
  README.md
Labels: new-framework

#136 Update README.md - Add Everything Search to File Systems section
  README.md
Labels: New server

#141 Add SecretiveShell/MCP-timeserver
  README.md
Labels: New server

#140 Add Alpha Vantage mcp server
  README.md
Labels: New server

#145 Add SecretiveShell/MCP-wolfram-alpha
  README.md
Labels: New server

#146 Update README.md – Add mcp-zotero
  README.md
Labels: New server

#148 adding mcp geo
  README.md
Labels: New server

#149 Add SearXNG MCP to the README.md
  README.md
Labels: New server

#150 feat: Added new website-downloader mcp server
  README.md
Labels: New server

#156 add mcp-difyworkflow-server
  README-ja.md
  README-zh.md
  README.md
Labels: New server

#157 Add DeepSeek
  README.md
Labels: documentation

#161 Added MCP Server for Hackernews
  README.md
Labels: New server
